[package]
name = "discv5"
authors = ["Age Manning <Age@AgeManning.com>"]
edition = "2018"
version = "0.1.0-beta.2"
description = "Implementation of the p2p discv5 discovery protocol"
license = "MIT"
repository = "https://github.com/sigp/discv5"
readme = "./README.md"
keywords = ["peer-to-peer", "libp2p", "networking", "discovery", "discv5"]
categories = ["network-programming", "asynchronous"]
exclude = [
	".gitignore",
	".github/*"
]

[dependencies]
enr = { git = "https://github.com/rust-ethereum/enr", features = ["k256", "ed25519"] }
tokio = { version = "1.0", features = ["net", "sync", "macros"] }
tokio-stream = "0.1.0"
tokio-util = { version = "0.6.0", features = ["time"] }
libp2p-core = { version = "0.25.1", optional = true }
zeroize = { version = "1.1.1", features = ["zeroize_derive"] }
futures = "0.3.8"
bytes = "1"
uint = { version = "0.9", default-features = false }
rlp = "0.5"
sha2 = "0.9.2"
hkdf = "0.10.0"
hex = "0.4.2"
fnv = "1.0.7"
arrayvec = "0.5.2"
digest = "0.9.0"
rand = "0.7.3"
smallvec = "1.5.0"
parking_lot = "0.11.1"
lru_time_cache = "0.11.2"
lazy_static = "1.4.0"
aes-gcm = "0.8.0"
aes-ctr = "0.6.0"
k256 = { version = "0.7", features = ["arithmetic", "ecdh", "sha2", "zeroize"] }
tracing = { version = "0.1.21", features = ["log"] }
tracing-subscriber = "0.2.15"

[dev-dependencies]
quickcheck = "0.9.2"
env_logger = "0.8.2"
hex-literal = "0.3.1"
simple_logger = "1.11.0"
tokio-util = { version = "0.6.0", features = ["time"] }
tokio = { version = "1.0", features = ["full"] }
rand_xorshift = "0.2.0"
rand_core = "0.5.1"

[features]
libp2p = ["libp2p-core"]
